### ISSUE TITLE
Build on macOS 10.13 and 10.14 broken: brewed subversion fails to install bc brewed openjdk build is broken

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#234]
Trying to build 6.3.0 on macOS 10.13, and I can't even get the build environment set up, because now the Homebrew subversion installation is broken, because it depends on openjdk and that is broken.

```
==> Installing dependencies for subversion: openjdk
==> Installing subversion dependency: openjdk
==> ./configure --disable-warnings-as-errors --with-boot-jdk-jvmargs=-Duser.home=/Users/janke/Library/Caches/Homebrew/java_cache --with-boot-jdk=/priva
==> make images
Last 15 lines from /Users/janke/Library/Logs/Homebrew/openjdk/02.make:
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
   ... (rest of output omitted)

* All command lines available in /private/tmp/openjdk-20211130-10638-swl1k4/jdk17u-jdk-17.0.1-ga/build/macosx-x86_64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [main] Error 2
make: *** [images] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
openjdk@8: depend on awk https://github.com/Homebrew/homebrew-core/pull/89982
openjdk@11 11.0.13 https://github.com/Homebrew/homebrew-core/pull/87638
openjdk: bump revision for gcc, fixes RPATH issue https://github.com/Homebrew/homebrew-core/pull/89642
OpenJDK is somewhat broken on newer MacOS instances, console is flooded with errors when using JMeter, AdoptOpenJDK has no issues https://github.com/Homebrew/homebrew-core/issues/66953

Error: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

hicks:~ janke$ 
```
[openjdk.zip](https://github.com/octave-app/octave-app/files/7625069/openjdk.zip)

From the build log:

```
Creating support/modules_libs/java.base/libjsig.dylib from 1 file(s)
In file included from src/java.base/macosx/native/libjava/java_props_macosx.c:32:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SystemConfiguration.h:126:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/SystemConfiguration.framework/Headers/SCPreferences.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:36:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:354:49: error: expected a version of the form 'major[.minor[.subminor]]'
                                    macos(10.3, API_TO_BE_DEPRECATED),
                                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
                                              ^
In file included from src/java.base/macosx/native/libjava/java_props_macosx.c:33:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:87:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:24:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:29:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AppleEvents.h:597:165: error: expected function body after function declarator
extern OSStatus AEDeterminePermissionToAutomateTarget( const AEAddressDesc* target, AEEventClass theAEEventClass, AEEventID theAEEventID, Boolean askUserIfNeeded ) __OSX_AVAILABLE_STARTING( __MAC_10_14, __IPHONE_NA );
                                                                                                                                                                    ^
/usr/include/Availability.h:216:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:11:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_14
^
In file included from src/java.base/macosx/native/libjava/java_props_macosx.c:33:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:179:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:21:27: error: expected a version of the form 'major[.minor[.subminor]]'
} NS_DEPRECATED_MAC(10_8, API_TO_BE_DEPRECATED, "All NSUserNotifications API should be replaced with UserNotifications.frameworks API");
                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:23:25: error: expected a version of the form 'major[.minor[.subminor]]'
NS_DEPRECATED_MAC(10_8, API_TO_BE_DEPRECATED, "All NSUserNotifications API should be replaced with UserNotifications.frameworks API")
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:102:26: error: expected a version of the form 'major[.minor[.subminor]]'
NS_DEPRECATED_MAC(10_10, API_TO_BE_DEPRECATED, "All NSUserNotifications API should be replaced with UserNotifications.frameworks API")
                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:115:95: error: expected a version of the form 'major[.minor[.subminor]]'
FOUNDATION_EXPORT NSString * const NSUserNotificationDefaultSoundName NS_DEPRECATED_MAC(10_8, API_TO_BE_DEPRECATED, "All NSUserNotifications API should be replaced with UserNotifications.frameworks API") API_UNAVAILABLE(ios, watchos, tvos);
                                                                                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:117:25: error: expected a version of the form 'major[.minor[.subminor]]'
NS_DEPRECATED_MAC(10_8, API_TO_BE_DEPRECATED, "All NSUserNotifications API should be replaced with UserNotifications.frameworks API")
                        ^
10 errors generated.
make[3]: *** [/private/tmp/openjdk-20211130-10638-swl1k4/jdk17u-jdk-17.0.1-ga/build/macosx-x86_64-server-release/support/native/java.base/libjava/java_props_macosx.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [java.base-libs] Error 2
make[2]: *** Waiting for unfinished jobs....

ERROR: Build failed for target 'images' in configuration 'macosx-x86_64-server-release' (exit code 2) 
Stopping sjavac server
```

**Comment by rdzman** [comment]
Any update on this? Just wondering if this is still what's holding up the 6.3.0 and 6.4.0 builds. And, thanks again for making these packages available.

**Comment by apjanke** [comment]
No update, sorry. Between my day job, and Covid, and Homebrew not supporting macOS 10.14 any more, and VMware Fusion just being an ass, things are not looking good for a release here soon. I am currently looking at migrating the whole kit and caboodle over to MacPorts and soldiering on from there. I'm afraid you shouldn't expect anything useful here for a month or more. :(

**Comment by apjanke** [comment]
(Not that Homebrew or VMware Fusion are bad products. They are good; they either just don't do what I need for this particular use case, or I'm not sufficiently competent at using them. Either way, sorry.)

**Comment by jserafim** [comment]
Just in case this helps anyone, this is what I had to do to install subversion on macOS 10.13.

First, install temurin:
`$ brew install --cask temurin`

Then patch `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/subversion.rb`

```
--- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/subversion_broken.rb	2022-03-17 11:50:22.000000000 -0300
+++ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/subversion.rb	2022-03-17 11:50:56.000000000 -0300
@@ -34,7 +34,6 @@
     depends_on "gettext" => :build
   end

-  depends_on "openjdk" => :build
   depends_on "pkg-config" => :build
   depends_on "python@3.10" => :build
   depends_on "scons" => :build # For Serf
@@ -98,6 +97,10 @@
         "b'SERF_MINOR_VERSION ([0-9]+).*'"
         s.gsub! "'SERF_PATCH_VERSION ([0-9]+)'",
         "b'SERF_PATCH_VERSION ([0-9]+)'"
+        s.gsub! "tenv.Replace(RPATH=thisdir)", ""
+        s.gsub! "env.Append(RPATH=':'+d)", "break"
+        s.gsub! "env.Append(RPATH=libdir,", ""
+        s.gsub! "PDB='${TARGET.filebase}.pdb')", ""
       end

       # scons ignores our compiler and flags unless explicitly passed
@@ -154,7 +157,7 @@
       --with-apr-util=#{Formula["apr-util"].opt_prefix}
       --with-apr=#{Formula["apr"].opt_prefix}
       --with-apxs=no
-      --with-jdk=#{Formula["openjdk"].opt_prefix}
+      --with-jdk="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
       --with-ruby-sitedir=#{lib}/ruby
       --with-py3c=#{py3c_prefix}
       --with-serf=#{serf_prefix}
```


Note: the path `/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home` should be replaced by the output of `$ /usr/libexec/java_home`. This could probably be done automatically at the Homebrew formula for subversion, but I'm not familiar with Homebrew or ruby.

Finally:
`$ brew install subversion`

**Comment by apjanke** [comment]
Ah, cool: we could easily make a customized `subversion-octave-app` Subversion formula with this patch in the octave-app tap for building Octave. Thanks!

**Comment by hypersad** [comment]
can someone share their prebuilt version for hig_sierra

**Comment by hypersad** [comment]
I am not testing with high_sierra yet but it seems catalina build 7.2.0 is working on mojave

**Comment by apjanke** [comment]
Looks like this got fixed up in later versions of subversion or its Homebrew formula: I've had no issues installing subversion on macOS 11-14 while doing the Octave.app 8.x builds. Closing this as fixed. Please re-open if you still run in to problems here.
