### ISSUE TITLE
_mkostemp lazy binding failed when running on OS X 10.11

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#93]
When I run the 4.4.0 beta 6 pre-test build on an OS X 10.11 VM, I get an error on Octave startup, right after saying "Yes" to the "rebuild the font cache now?" that pops up on initial program startup.

<img width="419" alt="screen shot 2018-07-24 at 4 44 21 am" src="https://user-images.githubusercontent.com/2618447/43127046-773155c8-8efc-11e8-9535-362ad5b6783d.png">

```
dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
[...]
```

I suspect this is due to the fontconfig package being built for the newer version of OS X.

I don't think there's an easy way to handle this in Homebrew. They don't provide a way of specifying the version of the OS X SDK to link against, since building redistributables (besides bottles) isn't a supported use of Homebrew. For their bottles, they just have a build box that's running the exact OS for each of their target OSes.

I'll fiddle around with the fontconfig formula a bit on this, but the easiest solution is probably just to install an older version of OS X on the Core2 build box when it arrives, and use that for project builds.

**Comment by Izbear125** [comment]
I have been successfully running octave 3.4.0 on mac os x 10.11.
I upgraded to octave-4.4.1 and successfully ran computations without graphics.  When I tried a simple plot(x,y) resulted in the following error message
octave:3> plot(x,y);

dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/fontconfig/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/fontconfig/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
fatal: caught signal Trace/BPT trap: 5 -- stopping myself...
fatal: caught signal Segmentation fault: 11 -- stopping myself...
Segmentation fault
